### ISSUE TITLE
Improve the output format

### ISSUE THREAD

**Issue by vasugr** [vasugr/weather_forecast#26]
Make the output better, currently the output is just plain and boring

Explore the following to show output in table format 
- https://github.com/Leviathan1995/Pylsy#
- https://pypi.org/project/terminaltables/

**Comment by ducdamchi** [comment]
I'd like to work on this!

**Comment by vasugr** [comment]
@ducdamchi Great! Do take a latest pull once

**Comment by ducdamchi** [comment]
I adjusted the code incorporating the latest pull, it should work now! 
https://github.com/vasugr/weather_forecast/pull/29
