### ISSUE TITLE
Scrape more information

### ISSUE THREAD

**Issue by vasugr** [vasugr/weather_forecast#27]
Scrape more information from the page 
- Temperature
- Clouds

<img width="339" alt="image" src="https://github.com/user-attachments/assets/68c435bc-83cd-49d8-9a15-8d6e42294ae2">

**Comment by ducdamchi** [comment]
I can work on this as well.

**Comment by ducdamchi** [comment]
Please let me know if this works.
https://github.com/vasugr/weather_forecast/pull/29
<img width="952" alt="infoscrape" src="https://github.com/user-attachments/assets/84f989fb-e16e-4711-941a-b7d8661f9caa">
